name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v6
      - name: List Repo Files
        run: ls -ltra
      - name: Executing shell script
        run: 
          chmod +x ascii-script.sh
          ./ascii-script.sh
    #  - name: my-step
     #   run: echo "Hello World!"
     # - name: List files
     #   run: ls
    #  - name: Read file
     #   run: cat README.md  
